#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'taobao_types'

    module TaobaoThrift
      module ICService
        class Client
          include ::Thrift::Client

        end

        class Processor
          include ::Thrift::Processor

        end

        # HELPER FUNCTIONS AND STRUCTURES

      end

    end
